name: Bumpify Dependencies
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dependency Bump Action
        uses: jbigman/bumpify@main
        with:
          token: ${{ secrets.PAT_FOR_PULL_REQUEST }}