name: Run tests on pull request
on:
  pull_request:

jobs:
  build:
    name: Run tests on pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: npm test